name: integration_test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  integration_test:
    if: github.repository == 'cloudquery/cq-provider-digitalocean'
    strategy:
      matrix:
        dbversion: [ "postgres:latest" ]
        go: [ "1.17" ]
        platform: [ ubuntu-latest ] # can not run in macOS and widnowsOS
    runs-on: ${{ matrix.platform }}
    services:
      postgres:
        image: ${{ matrix.dbversion }}
        env:
          POSTGRES_PASSWORD: pass
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Build
        run: go build -v .

      - name: Integration Test
        run: |
          touch output.log
          go test -v -p 20 ./resources/integration_tests | tee output.log
          result_code=${PIPESTATUS[0]}
          echo "::set-output name=output::$(cat output.log | grep -i "WARN")"
          exit $result_code
        env:
          INTEGRATION_TESTS: 1
          TF_VAR_SUFFIX: integration
          TF_VAR_PREFIX: cq-testing
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          SPACES_ACCESS_KEY_ID: ${{ secrets.SPACES_ACCESS_KEY_ID }}
          SPACES_SECRET_ACCESS_KEY: ${{ secrets.SPACES_SECRET_ACCESS_KEY }}
          CQ_NO_TELEMETRY: 1

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        if: ${{ failure() }}
        env:
          SLACK_CHANNEL: oss-tests
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: 'DigitalOcean - E2E tests failed'
          SLACK_TITLE: DigitalOcean - E2E test failed
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: Slack Notification Warnings
        uses: rtCamp/action-slack-notify@v2
        if: ${{ success() && steps.integration-test.outputs.output != '' }}
        env:
          SLACK_CHANNEL: oss-tests
          SLACK_COLOR: "#f29a35"
          SLACK_MESSAGE: "${{steps.integration-test.outputs.output}}\n\n For more details, please check the logs: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"
          SLACK_TITLE: DigitalOcean - E2E tests finished with warnings
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: Cancel if has warnings
        if: ${{ success() && steps.integration-test.outputs.output != '' }}
        run: exit 1